create table vix_c_component (
id          number(8,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
file_prefix varchar2(30) not null,
abbrev      varchar2(30) not null,
name        nvarchar2(80) not null,  
unit        nvarchar2(50) not null
);
create unique index uq_vix_c_component_01 on vix_c_component (file_prefix);
create unique index uq_vix_c_component_02 on vix_c_component (abbrev);
insert into vix_c_component (file_prefix,abbrev,name,unit) values ('VI','VI','Ventilační index','m²·s⁻¹');
insert into vix_c_component (file_prefix,abbrev,name,unit) values ('T','T2m','Teplota vzduchu','K');

alter table vix_p_primary_data add id_component number(8,0);
update vix_p_primary_data set id_component=1;
alter table vix_p_primary_data modify id_component not null;
alter table vix_p_primary_data modify id_component default 1;
alter table vix_p_primary_data add constraint fk_vix_p_primary_data_01 foreign key (id_component)  references vix_c_component  (id);

alter table vix_s_secondary_data add id_component number(8,0);
update vix_s_secondary_data set id_component=1;
alter table vix_s_secondary_data modify id_component not null;
alter table vix_s_secondary_data modify id_component default 1;
alter table vix_s_secondary_data add constraint fk_vix_s_secondary_data_01 foreign key (id_component)  references vix_c_component  (id);

alter table vix_c_data_record add id_component number(8,0);
update vix_c_data_record set id_component=1;
alter table vix_c_data_record modify id_component not null;
alter table vix_c_data_record modify id_component default 1;
alter table vix_c_data_record add constraint fk_vix_c_data_record_01 foreign key (id_component)  references vix_c_component  (id);

alter table vix_c_aggreg_type add unit nvarchar2(50);
update vix_c_aggreg_type set unit = 'm²·s⁻¹' where fixed_id in (1,2,3);
update vix_c_aggreg_type set unit = '%' where fixed_id >3 and fixed_id < 16;
alter table vix_c_aggreg_type modify unit not null;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (16,16,(select id from vix_c_interval where abbrev='1d'),'avg(1h)/1d)','Den: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (17,17,(select id from vix_c_interval where abbrev='1m'),'avg(1h)/1m)','Měsíc: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (18,18,(select id from vix_c_interval where abbrev='1y'),'avg(1h)/1y)','Rok: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');
exit;



