drop table vix_c_data_record cascade constraint;
create table VIX_C_DATA_RECORD
(
  id           NUMBER(8) generated by default as identity,
  id_area      NUMBER(8) not null,
  id_component NUMBER(8) not null,
  start_time   DATE not null,
  end_time     DATE not null
);
alter table vix_c_data_record          add constraint pk_vix_c_data_record     primary key (id) ;
alter table VIX_C_DATA_RECORD add constraint FK_VIX_C_DATA_RECORD_01 foreign key (ID_COMPONENT) references VIX_C_COMPONENT (ID);
alter table VIX_C_DATA_RECORD add constraint FK_VIX_C_DATA_RECORD_02 foreign key (ID_AREA) references VIX_C_AREA (ID);
grant select,insert,update,delete on vix_c_data_record to vix_rw_role;


exit;