drop table grid_c_region cascade constraint;
create table grid_c_region
(
   id         number(8,0) not null ,
   code       varchar2(20 CHAR) not null ,
   name       varchar2(80 CHAR) not null
);
alter table grid_c_region add constraint pk_grid_c_region        primary key (id) ;
create unique index uq_grid_c_region_01 on grid_c_region (code);
grant select,insert,update,delete on grid_c_region to vix_rw_role;

drop table grid_c_component cascade constraint;
create table grid_c_component
(
   id         number(8,0) not null ,
   code       varchar2(20 CHAR) not null ,
   name       varchar2(80 CHAR) not null ,
   unit       varchar2(50 CHAR) not null
);
alter table grid_c_component add constraint pk_grid_c_component primary key (id) ;
create unique index uq_grid_c_component_01 on grid_c_component (code);
grant select,insert,update,delete on grid_c_component to vix_rw_role;

drop table grid_c_database cascade constraint;
create table grid_c_database
(
   id         number(8,0) not null ,
   code       varchar2(20 CHAR) not null ,
   name       varchar2(80 CHAR) not null
);
alter table grid_c_database add constraint pk_grid_c_database primary key (id) ;
create unique index uq_grid_c_database_01 on grid_c_database (code);
grant select,insert,update,delete on grid_c_database to vix_rw_role;

drop table grid_c_grid_cell cascade constraint;
create table grid_c_grid_cell
(
   id NUMBER(8,0) generated by default as identity,
   grid_number number(6,0) not null
);
alter table grid_c_grid_cell add constraint pk_grid_c_grid_cell primary key (id) ;
create unique index uq_grid_c_grid_cell_01 on grid_c_grid_cell (grid_number);
grant select,insert,update,delete on grid_c_grid_cell to vix_rw_role;

drop table grid_c_region_grid_cell cascade constraint;
create table grid_c_region_grid_cell
(
   id NUMBER(8,0) generated by default as identity,
   id_region number(8,0) not null,
   id_grid_cell number(8,0) not null
);
alter table grid_c_region_grid_cell add constraint pk_grid_c_regfion_grid_cell primary key (id) ;
create unique index uq_grid_c_region_grid_cell_01 on grid_c_region_grid_cell (id_region,id_grid_cell);
grant select,insert,update,delete on grid_c_region_grid_cell to vix_rw_role;
alter table grid_c_region_grid_cell add constraint   fk_grid_c_region_grid_cell_01 foreign key (id_region) references grid_c_region (id);
alter table grid_c_region_grid_cell add constraint   fk_grid_c_region_grid_cell_02 foreign key (id_grid_cell) references grid_c_grid_cell (id);

drop table grid_c_station cascade constraint;
create table grid_c_station
(
   id NUMBER(8,0) generated by default as identity,
   code varchar2(10 CHAR) not null,
   name varchar2(80 CHAR) not null,
   id_grid_cell number(8,0) not null ,
   id_database number(8,0) not null ,
   description varchar2(2000 CHAR)
);
alter table grid_c_station             add constraint pk_grid_c_station primary key (id) ;
create unique index indx_grid_c_station_01  on grid_c_station (code);
alter table grid_c_station add constraint   fk_grid_c_station_01 foreign key (id_grid_cell) references grid_c_grid_cell (id);
alter table grid_c_station add constraint   fk_grid_c_station_02 foreign key (id_database)  references grid_c_database (id);
grant select,insert,update,delete on grid_c_station to vix_rw_role;

drop table grid_p_primary_data cascade constraint;
create table grid_p_primary_data
(
   id_grid_cell number(8,0) not null ,
   id_component number(8,0) not null ,
   end_time date not null,
   value float not null   
);
alter table grid_p_primary_data add constraint pk_grid_p_primary     primary key (id_grid_cell,id_component,end_time) ;
alter table grid_p_primary_data add constraint fk_grid_p_primary_01  foreign key (id_grid_cell) references grid_c_grid_cell (id);
alter table grid_p_primary_data add constraint fk_grid_p_primary_02  foreign key (id_component) references grid_c_component (id);

grant select,insert,update,delete on grid_p_primary_data to vix_rw_role;


exit;
