drop table vix_c_region_grid cascade constraint;
create table vix_c_region_grid
(
   id         number(8,0) not null ,
   code       nvarchar2(20) not null ,
   name       nvarchar2(80) not null
);
alter table vix_c_region_grid             add constraint pk_vix_c_region_grid        primary key (id) ;
grant select,insert,update,delete on vix_c_region_grid to vix_rw_role;

drop table vix_c_component_grid cascade constraint;
create table vix_c_component_grid
(
   id         number(8,0) not null ,
   code       nvarchar2(20) not null ,
   name       nvarchar2(80) not null ,
   unit       nvarchar2(50) not null
);
alter table vix_c_component_grid add constraint pk_vix_c_component_grid primary key (id) ;
grant select,insert,update,delete on vix_c_component_grid to vix_rw_role;

drop table vix_c_database_grid cascade constraint;
create table vix_c_database_grid
(
   id         number(8,0) not null ,
   code       nvarchar2(20) not null ,
   name       nvarchar2(80) not null
);
alter table vix_c_database_grid add constraint pk_vix_c_database_grid primary key (id) ;
grant select,insert,update,delete on vix_c_database_grid to vix_rw_role;

drop table vix_c_station_grid cascade constraint;
create table vix_c_station_grid
(
   id NUMBER(8,0) generated by default as identity,
   code varchar2(6) not null,
   name nvarchar2(80) not null,
   id_region_grif number(8,0) not null ,
   id_database_grid number(8,0) not null ,
   grid_number number(6,0) not null,
   description nvarchar2(2000)
);
alter table vix_c_station_grid             add constraint pk_vix_c_station_grid primary key (id) ;
create unique index indx_vix_c_station_grid_01  on vix_c_station_grid (code);
alter table vix_c_station_grid add constraint   fk_vix_c_station_grid_01 foreign key (id_region_grid) references vix_c_region_grid (id);
alter table vix_c_station_grid add constraint   fk_vix_c_station_grid_02 foreign key (id_database_grid) references vix_c_database_grid (id);
grant select,insert,update,delete on vix_c_station_grid to vix_rw_role;

drop table vix_p_primary_data_grid cascade constraint;
create table vix_p_primary_data_grid
(
   id_station_grid number(8,0) not null ,
   id_component_grid number(8,0) not null ,
   id_value_type number(8,0) not null ,
   end_time date not null,
   value float not null   
);
alter table vix_p_primary_data_grid add constraint pk_p_primary_data_grid     primary key (id_station_grid,id_component_grid,id_value_type,end_time) ;
alter table vix_p_primary_data_grid add constraint fk_p_primary_data_grid_01  foreign key (id_station_grid) references vix_c_station_grid (id);
alter table vix_p_primary_data_grid add constraint fk_p_primary_data_grid_02  foreign key (id_component_grid) references vix_c_component_grid (id);
alter table vix_p_primary_data_grid add constraint fk_p_primary_data_grid_03  foreign key (id_value_type) references vix_c_value_type (id);
grant select,insert,update,delete on vix_p_primary_data_grid to vix_rw_role;


exit;

/*
create role vix_rw_role;
grant vix_rw_role to pollution with admin option;
grant vix_rw_role to novak with admin option;
grant vix_rw_role to novakv with admin option;
grant m_read_role to novak with admin option;
grant e_read_role to novak with admin option;
grant vix_rw_role to novak with admin option;

grant m_read_role to novakv with admin option;
grant e_read_role to novakv with admin option;
grant vix_rw_role to novakv with admin option;
*/