drop table vix_c_interval cascade constraint;
create table vix_c_interval
(
   id         number(8,0) not null ,
   interval   nvarchar2(19) not null ,
   abbrev     nvarchar2(10) not null
);
alter table vix_c_interval             add constraint pk_vix_c_interval        primary key (id) ;
grant select,insert,update,delete on vix_c_interval to vix_rw_role;

drop table vix_c_aggreg_type cascade constraint;
create table vix_c_aggreg_type
(
   id number(8,0) not null ,
   fixed_id number(4) not null,
   id_interval number(8,0) not null ,
   abbrev varchar2(20) not null,
   name nvarchar2(80) not null,
   description  nvarchar2(1600) not null,
   unit nvarchar2(50) not null
);
alter table vix_c_aggreg_type          add constraint pk_c_aggreg_type         primary key (id) ;
create unique index indx_vix_c_aggreg_type          on vix_c_aggreg_type (fixed_id);
alter table vix_c_aggreg_type add constraint fk_vix_c_aggreg_type_01  foreign key (id_interval) references vix_c_interval (id);
grant select,insert,update,delete on vix_c_aggreg_type to vix_rw_role;

drop table vix_c_area cascade constraint;
create table vix_c_area
(
   id number(8,0) not null ,
   fixed_id number(4) not null,
   code varchar2(6) not null,
   name nvarchar2(80) not null
);
alter table vix_c_area                 add constraint pk_c_area                primary key (id) ;
create unique index indx_vix_c_area_01              on vix_c_area (fixed_id);
create unique index indx_vix_c_area_02              on vix_c_area (code);
grant select,insert,update,delete on vix_c_area to vix_rw_role;

drop table vix_c_value_type cascade constraint;
create table vix_c_value_type
(
   id number(8,0) not null ,
   fixed_id number(4) not null,
   abbrev varchar2(20) not null,
   name nvarchar2(80) not null,
   description  nvarchar2(1600) not null
);
alter table vix_c_value_type           add constraint pk_c_value_type          primary key (id) ;
create unique index indx_vix_c_value_type           on vix_c_value_type (fixed_id);
grant select,insert,update,delete on vix_c_value_type to vix_rw_role;

drop table vix_c_class cascade constraint;
create table vix_c_class
(
   id number(8,0) not null ,
   code         varchar2(6) not null,
   name         nvarchar2(80) not null,
   description  nvarchar2(1600) not null,
   value_from   float not null,
   value_to     float
);
alter table vix_c_class      add constraint pk_c_class    primary key (id) ;
create unique index indx_vix_c_class  on vix_c_class (code);
grant select,insert,update,delete on vix_c_class to vix_rw_role;

drop table vix_c_data_record cascade constraint;
create table VIX_C_DATA_RECORD
(
  id           NUMBER(8) generated by default as identity,
  id_area      NUMBER(8) not null,
  id_component NUMBER(8) not null,
  start_time   DATE not null,
  end_time     DATE not null
);
alter table vix_c_data_record          add constraint pk_vix_c_data_record     primary key (id) ;
alter table VIX_C_DATA_RECORD add constraint FK_VIX_C_DATA_RECORD_01 foreign key (ID_COMPONENT) references VIX_C_COMPONENT (ID);
alter table VIX_C_DATA_RECORD add constraint FK_VIX_C_DATA_RECORD_02 foreign key (ID_AREA) references VIX_C_AREA (ID);
grant select,insert,update,delete on vix_c_data_record to vix_rw_role;

drop table vix_c_component cascade constraint;
create table vix_c_component (
id          number(8,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
file_prefix varchar2(30) not null,
abbrev      varchar2(30) not null,
name        nvarchar2(80) not null,  
unit        nvarchar2(50) not null
);
grant select,insert,update,delete on vix_c_component to vix_rw_role;

drop table vix_p_primary_data cascade constraint;
create table vix_p_primary_data
(
   id_area number(8,0) not null ,
   start_time date not null,
   id_value_type number(8,0) not null ,
   value float not null   
);
alter table vix_p_primary_data         add constraint pk_p_primary_data        primary key (id_area,id_component,start_time,id_value_type) ;
alter table vix_p_primary_data add constraint fk_p_primary_data_01  foreign key (id_area) references vix_c_area (id);
alter table vix_p_primary_data add constraint fk_p_primary_data_0   foreign key (id_component) references vix_c_component (id);
alter table vix_p_primary_data add constraint fk_p_primary_data_03  foreign key (id_value_type) references vix_c_value_type (id);
grant select,insert,update,delete on vix_p_primary_data to vix_rw_role;

drop table vix_s_secondary_data cascade constraint;
create table vix_s_secondary_data
(
   id_area number(8,0) not null ,
   start_time date not null,
   id_aggreg_type number(8,0) not null ,
   id_component number(8,0) not null ,
   value float
);
alter table vix_s_secondary_data       add constraint pk_s_secondary_data      primary key (id_area,id_component,start_time,id_aggreg_type) ;
alter table vix_s_secondary_data add constraint fk_s_secondary_data_01  foreign key (id_area) references vix_c_area (id);
alter table vix_s_secondary_data add constraint fk_s_secondary_data_02  foreign key (id_aggreg_type) references vix_c_aggreg_type (id);
alter table vix_s_secondary_data add constraint fk_s_secondary_data_03  foreign key (id_component) references vix_c_component (id);
grant select,insert,update,delete on vix_s_secondary_data to vix_rw_role;


drop sequence vix_id_data_record;
create sequence vix_id_data_record
minvalue 1
maxvalue 99999999
start with 1
increment by 1
cache 10
cycle
;
grant select on vix_id_data_record to vix_rw_role;



insert into vix_c_component (file_prefix,abbrev,name,unit) values ('VI','VI','Ventilační index','m²·s⁻¹');
insert into vix_c_component (file_prefix,abbrev,name,unit) values ('T','T2m','Teplota vzduchu','K');

delete from vix_c_aggreg_type;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (1 ,1 ,1,'avg(1h)/1d','Den: aritmetický průměr ventilačních indexů','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','m²·s⁻¹') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (2 ,2 ,2,'avg(1h)/1m','Měsíc: aritmetický průměr ventilačních indexů','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','m²·s⁻¹') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (3 ,3 ,3,'avg(1h)/1y','Rok: aritmetický průměr ventilačních indexů','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','m²·s⁻¹') ;

insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (4 ,4 ,1,'%/1d VD','Den: Velmi dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (5 ,5 ,1,'%/1d D' ,'Den: Dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (6 ,6 ,1,'%/1d MN','Den: Mírně nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (7 ,7 ,1,'%/1d N' ,'Den: Nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;

insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (8 ,8 ,2,'%/1m VD','Měsíc: Velmi dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (9 ,9 ,2,'%/1m D' ,'Měsíc: Dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (10,10,2,'%/1m MN','Měsíc: Mírně nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (11,11,2,'%/1m N' ,'Měsíc: Nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;

insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (12,12,3,'%/1y VD','Rok: Velmi dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (13,13,3,'%/1y D' ,'Rok: Dobré RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (14,14,3,'%/1y MN','Rok: Mírně nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (15,15,3,'%/1y N' ,'Rok: Nepříznivé RP - četnosti v % podle OME','Zápis četnosti proběhne bez ohledu na množství dat','%') ;

insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (16,16,(select id from vix_c_interval where abbrev='1d'),'avg(1h)/1d)','Den: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (17,17,(select id from vix_c_interval where abbrev='1m'),'avg(1h)/1m)','Měsíc: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');
insert into vix_c_aggreg_type (id,fixed_id,id_interval,abbrev,name,description,unit) values (18,18,(select id from vix_c_interval where abbrev='1y'),'avg(1h)/1y)','Rok: aritmetický průměr teploty','Minimální počet dat pro provedení výpočtu je definován v databázi. Viz GagReport','K');

delete from vix_c_class;
insert into vix_c_class (id,class,code,name,description,value_from,value_to) values (1,1,'VD','Velmi dobré RP','četnost hodinových hodnot v %'     ,8600,null);
insert into vix_c_class (id,class,code,name,description,value_from,value_to) values (2,2,'D' ,'Dobré RP','četnost hodinových hodnot v %'           ,2800,8600);
insert into vix_c_class (id,class,code,name,description,value_from,value_to) values (3,3,'MN','Mírně nepříznivé RP','četnost hodinových hodnot v %',1700,2800);
insert into vix_c_class (id,class,code,name,description,value_from,value_to) values (4,4,'N' ,'Nepříznivé RP','četnost hodinových hodnot v %'      ,0,1700);



exit;

/*
create role vix_rw_role;
grant vix_rw_role to pollution with admin option;
grant vix_rw_role to novak with admin option;
grant vix_rw_role to novakv with admin option;
grant m_read_role to novak with admin option;
grant e_read_role to novak with admin option;
grant vix_rw_role to novak with admin option;

grant m_read_role to novakv with admin option;
grant e_read_role to novakv with admin option;
grant vix_rw_role to novakv with admin option;
*/
