delete from grid_p_primary_data;
delete from grid_c_station;
delete from grid_c_region_grid_cell;
delete from grid_c_grid_cell;

delete from grid_c_component;
insert into grid_c_component (id,code,name,unit) values (1 ,'PBL','výška mezní vrstvy','m') ;
insert into grid_c_component (id,code,name,unit) values (2 ,'T2m','teplota vzduchu','K') ;
insert into grid_c_component (id,code,name,unit) values (3 ,'VI','ventilační index','m²/s') ;

delete from grid_c_database;
insert into grid_c_database (id,code,name) values (1,'ISKO','Informační systém kvality ovzduší');
insert into grid_c_database (id,code,name) values (2,'Clidata','Meteorologické databáze');
insert into grid_c_database (id,code,name) values (3,'neurčeno','neurčeno');

delete from grid_c_region;
insert into grid_c_region (id,code,name) values (01, 'A', 'Praha');
insert into grid_c_region (id,code,name) values (02, 'S', 'Středočeský');
insert into grid_c_region (id,code,name) values (03, 'C', 'Jihočeský');
insert into grid_c_region (id,code,name) values (04, 'P', 'Plzeňský');
insert into grid_c_region (id,code,name) values (05, 'K', 'Karlovarský');
insert into grid_c_region (id,code,name) values (06, 'U', 'Ústecký');
insert into grid_c_region (id,code,name) values (07, 'L', 'Liberecký');
insert into grid_c_region (id,code,name) values (08, 'H', 'Královéhradecký');
insert into grid_c_region (id,code,name) values (09, 'E', 'Pardubický');
insert into grid_c_region (id,code,name) values (10, 'J', 'Vysočina');
insert into grid_c_region (id,code,name) values (11, 'B', 'Jihomoravský');
insert into grid_c_region (id,code,name) values (12, 'M', 'Olomoucký');
insert into grid_c_region (id,code,name) values (13, 'Z', 'Zlínský');
insert into grid_c_region (id,code,name) values (14, 'T', 'Moravskoslezský');

insert into grid_c_grid_cell (grid_number) values (520688);
insert into grid_c_grid_cell (grid_number) values (521743);
insert into grid_c_grid_cell (grid_number) values (517533);
insert into grid_c_grid_cell (grid_number) values (520690);
insert into grid_c_grid_cell (grid_number) values (521744);
insert into grid_c_grid_cell (grid_number) values (519637);
insert into grid_c_grid_cell (grid_number) values (521737);
insert into grid_c_grid_cell (grid_number) values (516478);
insert into grid_c_grid_cell (grid_number) values (518587);
insert into grid_c_grid_cell (grid_number) values (520690);
insert into grid_c_grid_cell (grid_number) values (517527);
insert into grid_c_grid_cell (grid_number) values (520690);
insert into grid_c_grid_cell (grid_number) values (519638);
insert into grid_c_grid_cell (grid_number) values (518581);
insert into grid_c_grid_cell (grid_number) values (522794);
insert into grid_c_grid_cell (grid_number) values (519637);
insert into grid_c_grid_cell (grid_number) values (521745);
insert into grid_c_grid_cell (grid_number) values (480773);
insert into grid_c_grid_cell (grid_number) values (487077);
insert into grid_c_grid_cell (grid_number) values (472321);
insert into grid_c_grid_cell (grid_number) values (469145);
insert into grid_c_grid_cell (grid_number) values (473335);
insert into grid_c_grid_cell (grid_number) values (458613);
insert into grid_c_grid_cell (grid_number) values (473356);
insert into grid_c_grid_cell (grid_number) values (474425);
insert into grid_c_grid_cell (grid_number) values (482850);
insert into grid_c_grid_cell (grid_number) values (475478);
insert into grid_c_grid_cell (grid_number) values (472318);
insert into grid_c_grid_cell (grid_number) values (474426);
insert into grid_c_grid_cell (grid_number) values (477584);
insert into grid_c_grid_cell (grid_number) values (475476);
insert into grid_c_grid_cell (grid_number) values (475480);
insert into grid_c_grid_cell (grid_number) values (474424);
insert into grid_c_grid_cell (grid_number) values (472321);
insert into grid_c_grid_cell (grid_number) values (473372);
insert into grid_c_grid_cell (grid_number) values (457593);
insert into grid_c_grid_cell (grid_number) values (458613);
insert into grid_c_grid_cell (grid_number) values (468121);
insert into grid_c_grid_cell (grid_number) values (453368);
insert into grid_c_grid_cell (grid_number) values (474430);
insert into grid_c_grid_cell (grid_number) values (475482);
insert into grid_c_grid_cell (grid_number) values (478648);
insert into grid_c_grid_cell (grid_number) values (456506);
insert into grid_c_grid_cell (grid_number) values (470119);
insert into grid_c_grid_cell (grid_number) values (490133);
insert into grid_c_grid_cell (grid_number) values (475407);
insert into grid_c_grid_cell (grid_number) values (479624);
insert into grid_c_grid_cell (grid_number) values (462774);
insert into grid_c_grid_cell (grid_number) values (464880);
insert into grid_c_grid_cell (grid_number) values (463828);
insert into grid_c_grid_cell (grid_number) values (470119);
insert into grid_c_grid_cell (grid_number) values (490133);
insert into grid_c_grid_cell (grid_number) values (481719);
insert into grid_c_grid_cell (grid_number) values (466972);
insert into grid_c_grid_cell (grid_number) values (479605);
insert into grid_c_grid_cell (grid_number) values (485948);
insert into grid_c_grid_cell (grid_number) values (475407);
insert into grid_c_grid_cell (grid_number) values (502857);
insert into grid_c_grid_cell (grid_number) values (517571);
insert into grid_c_grid_cell (grid_number) values (516519);
insert into grid_c_grid_cell (grid_number) values (518627);
insert into grid_c_grid_cell (grid_number) values (501785);
insert into grid_c_grid_cell (grid_number) values (513380);
insert into grid_c_grid_cell (grid_number) values (550214);
insert into grid_c_grid_cell (grid_number) values (532331);
insert into grid_c_grid_cell (grid_number) values (513380);
insert into grid_c_grid_cell (grid_number) values (512295);
insert into grid_c_grid_cell (grid_number) values (515465);
insert into grid_c_grid_cell (grid_number) values (501785);
insert into grid_c_grid_cell (grid_number) values (552321);
insert into grid_c_grid_cell (grid_number) values (543915);
insert into grid_c_grid_cell (grid_number) values (524945);
insert into grid_c_grid_cell (grid_number) values (523892);
insert into grid_c_grid_cell (grid_number) values (525997);
insert into grid_c_grid_cell (grid_number) values (525999);
insert into grid_c_grid_cell (grid_number) values (537566);
insert into grid_c_grid_cell (grid_number) values (548112);
insert into grid_c_grid_cell (grid_number) values (524958);
insert into grid_c_grid_cell (grid_number) values (532331);
insert into grid_c_grid_cell (grid_number) values (543901);
insert into grid_c_grid_cell (grid_number) values (533369);
insert into grid_c_grid_cell (grid_number) values (451199);
insert into grid_c_grid_cell (grid_number) values (484923);
insert into grid_c_grid_cell (grid_number) values (473335);
insert into grid_c_grid_cell (grid_number) values (494384);
insert into grid_c_grid_cell (grid_number) values (494384);
insert into grid_c_grid_cell (grid_number) values (483886);
insert into grid_c_grid_cell (grid_number) values (487017);
insert into grid_c_grid_cell (grid_number) values (475454);
insert into grid_c_grid_cell (grid_number) values (479654);
insert into grid_c_grid_cell (grid_number) values (493358);
insert into grid_c_grid_cell (grid_number) values (522732);
insert into grid_c_grid_cell (grid_number) values (530120);
insert into grid_c_grid_cell (grid_number) values (537483);
insert into grid_c_grid_cell (grid_number) values (526954);
insert into grid_c_grid_cell (grid_number) values (505915);
insert into grid_c_grid_cell (grid_number) values (501681);
insert into grid_c_grid_cell (grid_number) values (522733);
insert into grid_c_grid_cell (grid_number) values (528014);
insert into grid_c_grid_cell (grid_number) values (551231);
insert into grid_c_grid_cell (grid_number) values (562830);
insert into grid_c_grid_cell (grid_number) values (558615);
insert into grid_c_grid_cell (grid_number) values (556521);
insert into grid_c_grid_cell (grid_number) values (552303);
insert into grid_c_grid_cell (grid_number) values (556492);
insert into grid_c_grid_cell (grid_number) values (553353);
insert into grid_c_grid_cell (grid_number) values (547035);
insert into grid_c_grid_cell (grid_number) values (555467);
insert into grid_c_grid_cell (grid_number) values (552307);
insert into grid_c_grid_cell (grid_number) values (559666);
insert into grid_c_grid_cell (grid_number) values (494469);
insert into grid_c_grid_cell (grid_number) values (527093);
insert into grid_c_grid_cell (grid_number) values (501812);
insert into grid_c_grid_cell (grid_number) values (512345);
insert into grid_c_grid_cell (grid_number) values (494451);
insert into grid_c_grid_cell (grid_number) values (494452);
insert into grid_c_grid_cell (grid_number) values (492361);
insert into grid_c_grid_cell (grid_number) values (487087);
insert into grid_c_grid_cell (grid_number) values (488129);
insert into grid_c_grid_cell (grid_number) values (513397);
insert into grid_c_grid_cell (grid_number) values (494455);
insert into grid_c_grid_cell (grid_number) values (503938);
insert into grid_c_grid_cell (grid_number) values (492383);
insert into grid_c_grid_cell (grid_number) values (499743);
insert into grid_c_grid_cell (grid_number) values (523931);
insert into grid_c_grid_cell (grid_number) values (497601);
insert into grid_c_grid_cell (grid_number) values (519637);
insert into grid_c_grid_cell (grid_number) values (521746);
insert into grid_c_grid_cell (grid_number) values (516478);
insert into grid_c_grid_cell (grid_number) values (521737);
insert into grid_c_grid_cell (grid_number) values (494384);
insert into grid_c_grid_cell (grid_number) values (494405);
insert into grid_c_grid_cell (grid_number) values (486957);
insert into grid_c_grid_cell (grid_number) values (502763);
insert into grid_c_grid_cell (grid_number) values (503809);
insert into grid_c_grid_cell (grid_number) values (504862);
insert into grid_c_grid_cell (grid_number) values (505914);
insert into grid_c_grid_cell (grid_number) values (505916);
insert into grid_c_grid_cell (grid_number) values (503809);
insert into grid_c_grid_cell (grid_number) values (501681);
insert into grid_c_grid_cell (grid_number) values (495375);
insert into grid_c_grid_cell (grid_number) values (504850);
insert into grid_c_grid_cell (grid_number) values (514360);
insert into grid_c_grid_cell (grid_number) values (523841);
insert into grid_c_grid_cell (grid_number) values (523859);
insert into grid_c_grid_cell (grid_number) values (515438);
insert into grid_c_grid_cell (grid_number) values (513344);
insert into grid_c_grid_cell (grid_number) values (524894);
insert into grid_c_grid_cell (grid_number) values (523839);
insert into grid_c_grid_cell (grid_number) values (524892);
insert into grid_c_grid_cell (grid_number) values (516502);
insert into grid_c_grid_cell (grid_number) values (529111);
insert into grid_c_grid_cell (grid_number) values (537553);
insert into grid_c_grid_cell (grid_number) values (511223);
insert into grid_c_grid_cell (grid_number) values (500669);
insert into grid_c_grid_cell (grid_number) values (530190);
insert into grid_c_grid_cell (grid_number) values (526998);
insert into grid_c_grid_cell (grid_number) values (524895);
insert into grid_c_grid_cell (grid_number) values (512255);
insert into grid_c_grid_cell (grid_number) values (490280);
insert into grid_c_grid_cell (grid_number) values (514465);
insert into grid_c_grid_cell (grid_number) values (503938);
insert into grid_c_grid_cell (grid_number) values (502918);
insert into grid_c_grid_cell (grid_number) values (498698);
insert into grid_c_grid_cell (grid_number) values (503965);
insert into grid_c_grid_cell (grid_number) values (505017);
insert into grid_c_grid_cell (grid_number) values (513416);
insert into grid_c_grid_cell (grid_number) values (508181);
insert into grid_c_grid_cell (grid_number) values (508181);
insert into grid_c_grid_cell (grid_number) values (497647);
insert into grid_c_grid_cell (grid_number) values (507120);
insert into grid_c_grid_cell (grid_number) values (507119);
insert into grid_c_grid_cell (grid_number) values (508172);
insert into grid_c_grid_cell (grid_number) values (506066);
insert into grid_c_grid_cell (grid_number) values (507116);
insert into grid_c_grid_cell (grid_number) values (506063);
insert into grid_c_grid_cell (grid_number) values (508172);
insert into grid_c_grid_cell (grid_number) values (505015);
insert into grid_c_grid_cell (grid_number) values (506068);
insert into grid_c_grid_cell (grid_number) values (492380);
insert into grid_c_grid_cell (grid_number) values (512373);
insert into grid_c_grid_cell (grid_number) values (505012);
insert into grid_c_grid_cell (grid_number) values (494499);
insert into grid_c_grid_cell (grid_number) values (509228);
insert into grid_c_grid_cell (grid_number) values (500796);
insert into grid_c_grid_cell (grid_number) values (498707);
insert into grid_c_grid_cell (grid_number) values (498708);
insert into grid_c_grid_cell (grid_number) values (511336);
insert into grid_c_grid_cell (grid_number) values (539636);
insert into grid_c_grid_cell (grid_number) values (536452);
insert into grid_c_grid_cell (grid_number) values (544885);
insert into grid_c_grid_cell (grid_number) values (544894);
insert into grid_c_grid_cell (grid_number) values (551216);
insert into grid_c_grid_cell (grid_number) values (554405);
insert into grid_c_grid_cell (grid_number) values (532244);
insert into grid_c_grid_cell (grid_number) values (555433);
insert into grid_c_grid_cell (grid_number) values (539636);
insert into grid_c_grid_cell (grid_number) values (540666);
insert into grid_c_grid_cell (grid_number) values (552263);
insert into grid_c_grid_cell (grid_number) values (546992);
insert into grid_c_grid_cell (grid_number) values (543847);
insert into grid_c_grid_cell (grid_number) values (539605);
insert into grid_c_grid_cell (grid_number) values (542779);
insert into grid_c_grid_cell (grid_number) values (546985);
insert into grid_c_grid_cell (grid_number) values (556482);
insert into grid_c_grid_cell (grid_number) values (538590);
insert into grid_c_grid_cell (grid_number) values (549104);
insert into grid_c_grid_cell (grid_number) values (536452);
insert into grid_c_grid_cell (grid_number) values (550163);
insert into grid_c_grid_cell (grid_number) values (551215);
insert into grid_c_grid_cell (grid_number) values (551216);
insert into grid_c_grid_cell (grid_number) values (550163);
insert into grid_c_grid_cell (grid_number) values (564920);
insert into grid_c_grid_cell (grid_number) values (474454);
insert into grid_c_grid_cell (grid_number) values (488161);
insert into grid_c_grid_cell (grid_number) values (467097);
insert into grid_c_grid_cell (grid_number) values (477609);
insert into grid_c_grid_cell (grid_number) values (468133);
insert into grid_c_grid_cell (grid_number) values (488156);
insert into grid_c_grid_cell (grid_number) values (481839);
insert into grid_c_grid_cell (grid_number) values (476564);
insert into grid_c_grid_cell (grid_number) values (475511);

insert into grid_c_region_grid_cell (id_region,id_grid_cell)
SELECT distinct gcr.id as id_region,gcgc.id as id_grid_cell
from vix_c_station_grid sg
join vix_c_region_grid rg on rg.id=sg.id_region_grid
join grid_c_region gcr on gcr.code=rg.code
join grid_c_grid_cell gcgc on gcgc.grid_number=sg.grid_number;

insert into grid_c_station (code,name,id_grid_cell,id_database,description)
SELECT 
sg.code as station_code,sg.name as station_name,gcgl.id as id_grid_cell,gcd.id as id_database,sg.description
from vix_c_station_grid sg
join vix_c_database_grid dg on dg.id=sg.id_database_grid
join grid_c_database gcd on gcd.code=dg.code
join grid_c_grid_cell gcgl on gcgl.grid_number=sg.grid_number
join vix_c_region_grid vcr on vcr.id=sg.id_region_grid
join grid_c_region gcr on gcr.code=vcr.code
join grid_c_region_grid_cell gcrgc on gcrgc.id_region=gcr.id and gcrgc.id_grid_cell=gcgl.id
;

exit;
